In [7]:
import pandas as pd
from datetime import date

In [22]:
today = date.today()
dates = [date.strftime('%d-%m-%Y') for date in pd.date_range(start='2020-01-22', end=today)]

In [33]:
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/01-01-2021.csv", index_col=0)

In [31]:
df = df[['Country_Region', 'Confirmed', 'Deaths']]

In [34]:
df

,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
FIPS,,,,,,,,,,,,,
NaN,NaN,NaN,Afghanistan,2021-01-02 05:22:33,33.939110,67.709953,51526,2191,41727,0.0,Afghanistan,0.000000,4.252222
NaN,NaN,NaN,Albania,2021-01-02 05:22:33,41.153300,20.168300,58316,1181,33634,23501.0,Albania,2026.409062,2.025173
NaN,NaN,NaN,Algeria,2021-01-02 05:22:33,28.033900,1.659600,99897,2762,67395,29740.0,Algeria,227.809861,2.764848
NaN,NaN,NaN,Andorra,2021-01-02 05:22:33,42.506300,1.521800,8117,84,7463,570.0,Andorra,10505.403482,1.034865
NaN,NaN,NaN,Angola,2021-01-02 05:22:33,-11.202700,17.873900,17568,405,11146,6017.0,Angola,53.452981,2.305328
...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,Zambia,2021-01-02 05:22:33,-13.133897,27.849332,20997,390,18773,1834.0,Zambia,114.213720,1.857408
NaN,NaN,NaN,Zimbabwe,2021-01-02 05:22:33,-19.015438,29.154857,14084,369,11347,2368.0,Zimbabwe,94.759262,2.619994
2066.0,Copper River,Alaska,US,2021-04-02 15:13:53,60.388600,-162.890520,157,0,0,0.0,"Copper River, Alaska, US",NaN,NaN
2063.0,Chugach,Alaska,US,2021-04-02 15:13:53,61.166660,-149.900000,221,3,0,0.0,"Chugach, Alaska, US",NaN,NaN
NaN,NaN,Unknown,China,2021-01-02 05:22:33,NaN,NaN,0,0,0,0.0,"Unknown, China",0.000000,0.000000